### ISSUE TITLE
В чем отличие от оригинальной TVOut?

### ISSUE THREAD

**Issue by khusamov** [amperka/TVout#2]
Здравствуйте!
А в чем отличие вашей библиотеки от оригинала?
https://github.com/Avamander/arduino-tvout

Кроме переименования функций в camelCase-вариант.

**Comment by nomad605dis** [comment]
Добрый день!

Наша библиотека практически не отличается от оригинала. Мы сделали пару косметических украшений и фиксов под свои нужды. Так что вы в своих проектах можете использовать любой вариант.
